image: golang:1.18

variables:
  MANIFEST_PATH: .manifest.json

publish:
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - MODULE_NAME=$(jq -r '.config.languageOptions.go.goModuleName' $MANIFEST_PATH)
    - go mod download
    - GOPROXY=proxy.golang.org go list -m $MODULE_NAME
